### ISSUE TITLE
RequestType and ResponseType are not implemented in ocpp._2020.03

### ISSUE THREAD

**Issue by we6288815** [RWTH-i5-IDSG/ocpp-jaxb#4]
Hi, 
I found that the two interfaces, RequestType and ResponseType, are not implemented in ocpp._2020._03. What are the considerations that lead to them not being implemented?
Looking forward to your reply, thank you.

**Comment by goekay** [comment]
they are abstractions specific to [steve](https://github.com/RWTH-i5-IDSG/steve) to make my life easier. since i don't know how to approach the implementation of this ocpp version in steve, i left them out for this first iteration. nevertheless, i wanted to provide the java model for the ocpp 2.0.1 to people that might be interested in it.

**Comment by we6288815** [comment]
> they are abstractions specific to [steve](https://github.com/RWTH-i5-IDSG/steve) to make my life easier. since i don't know how to approach the implementation of this ocpp version in steve, i left them out for this first iteration. nevertheless, i wanted to provide the java model for the ocpp 2.0.1 to people that might be interested in it.

Thank you, I will study how to use them better in OCPP2.0.1.
